- include_tasks:
    file: setup.yml
    apply:
      tags:
        - ceproject.setup
  tags: always

- include_tasks:
    file: run.yml
    apply:
      tags:
        - ceproject.run
  tags: always

- include_tasks:
    file: apache.yml
    apply:
      tags:
        - ceproject.apache
  tags: always
